name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cmdstanVersion:
          - "2.31.0"
          - "2.30.1"
          - "2.30.0"
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    name: Package tests and linting
    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"
      - name: Install cmdstanpy
        run: pip install cmdstanpy
      - name: Compile cmdstan
        run: python -m cmdstanpy.install_cmdstan --version ${{ matrix.cmdstanVersion }} --verbose
      - name: Build release artifact
        run: tar -czvf cmdstan-${{ matrix.os }}-${{ matrix.cmdstanVersion }}.tar.gz -C ~/.cmdstan cmdstan-${{ matrix.cmdstanVersion }}
      - name: Upload the artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cmdstan-${{ matrix.os }}-${{ matrix.cmdstanVersion }}
          files: cmdstan-${{ matrix.os }}-${{ matrix.cmdstanVersion }}.tar.gz
          body: cmdstan-${{ matrix.cmdstanVersion }} compiled on ${{ matrix.os }}.
